spring:
  application:
    name: HotelManagement
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_management_db
    username: root
    password: 123456
    initialization-mode: always
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

mybatis:
  mapper-locations: classpath:mybatis/*.xml    # mybatis mapper映射文件位置